/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui_proj_inz;

import connection.transmiter.BaseTransmHandler;
import printer.PrinterSettings;

/**
 *
 * @author User
 */
public class MainGui extends javax.swing.JFrame {

    BaseTransmHandler baseTransmHandler = null;
    PrinterSettings printerSettings = new PrinterSettings(9600, null);

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        connectButton = new javax.swing.JToggleButton();
        commandLine = new javax.swing.JTextField();
        sendCommandButton = new javax.swing.JButton();
        xyDpadButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logList = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKonfiguracja = new javax.swing.JMenu();
        menuItemParametryDrukarki = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        connectButton.setText("Połącz");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        commandLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandLineActionPerformed(evt);
            }
        });

        sendCommandButton.setText("Wyślij");
        sendCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCommandButtonActionPerformed(evt);
            }
        });

        xyDpadButton.setBackground(new java.awt.Color(255, 255, 255));
        xyDpadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/d-pad.png"))); // NOI18N
        xyDpadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xyDpadButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(connectButton)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(commandLine)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(sendCommandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(xyDpadButton))
                                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(connectButton)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sendCommandButton)
                                        .addComponent(commandLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(xyDpadButton)
                                .addContainerGap(180, Short.MAX_VALUE))
        );

        logList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(logList);

        menuKonfiguracja.setText("Konfiguracja");

        menuItemParametryDrukarki.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemParametryDrukarki.setText("Parametry drukarki");
        menuItemParametryDrukarki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemParametryDrukarkiActionPerformed(evt);
            }
        });
        menuKonfiguracja.add(menuItemParametryDrukarki);

        jMenuBar1.add(menuKonfiguracja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void menuItemParametryDrukarkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemParametryDrukarkiActionPerformed
        ParametryDrukarkiForm parametryDrukarkiForm = new ParametryDrukarkiForm(settings -> {
            System.out.println("Chosen settings profile: " + settings.getProfileName());
            // TODO Handle the chosen settings profile here
        });
        parametryDrukarkiForm.setVisible(true);
    }//GEN-LAST:event_menuItemParametryDrukarkiActionPerformed

    private void commandLineActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //check if is pressed
        if (connectButton.isSelected()) {
            baseTransmHandler = new BaseTransmHandler(printerSettings.getSerialPort(), printerSettings.getBaudRate());
//            baseTransmHandler.start();
        } else {
//            baseTransmHandler.stop();
        }
    }

    private void xyDpadButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void sendCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {
    }  //GEN-LAST:event_sendButtonActionPerformed

    // Variables declaration - do not modify
    private javax.swing.JTextField commandLine;
    private javax.swing.JToggleButton connectButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> logList;
    private javax.swing.JMenuItem menuItemParametryDrukarki;
    private javax.swing.JMenu menuKonfiguracja;
    private javax.swing.JButton sendCommandButton;
    private javax.swing.JLabel xyDpadButton;
    // End of variables declaration

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new MainGui().setVisible(true);
        });

        //delete
    }
}
