package com.mycompany.gui_proj_inz;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.fazecast.jSerialComm.*;
import printer.PrinterSettings;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.Arrays;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class ParametryDrukarkiForm extends javax.swing.JFrame {

    private SerialPort[] portsList;
    private Integer[] baudRates = {9600, 19200, 38400, 57600, 115200};
    private String settingsPath = PrinterSettings.DEFAULT_PROFILE_PATH;

    private PrinterSettings chosenSettingsProfile = new PrinterSettings(9600, null);
    /**
     * Creates new form ParametryDrukarkiForm
     */
    public ParametryDrukarkiForm(Consumer<PrinterSettings> onCloseCallback) {
        initComponents();
        File profilesDir = new File(settingsPath);
        File[] profileFiles = profilesDir.listFiles((_, name) -> name.endsWith(".json"));
        //check if array empty
        if (profileFiles != null && profileFiles.length > 0) {
            for (File profileFile : profileFiles) {
                settingsProfileCombo.addItem(profileFile.getName().substring(0, profileFile.getName().length() - 5));
            }
            String profileName = settingsProfileCombo.getItemAt(0);
            System.out.println("First profile: " + profileName);
            chosenSettingsProfile = PrinterSettings.readProfileFromFile(settingsPath, profileName);
            if(chosenSettingsProfile != null && chosenSettingsProfile.getProfileName() != null) {
                System.out.println("Chosen profile combo: " + chosenSettingsProfile.getProfileName());
                settingsProfileCombo.setSelectedItem(chosenSettingsProfile.getProfileName());
            }
        }
        else {
            Logger.getGlobal().warning("No profiles found in " + settingsPath);
            settingsProfileCombo.addItem("Default");
        }

        manageCOMPorts();

        jComboBox3.removeAllItems();
        for (Integer baudRate : baudRates) {
            jComboBox3.addItem(baudRate.toString());
        }

        settingsProfileCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSettingsProfileComboActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // zamknięcie okna nie kończy działania programu
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Call the callback with chosenSettingsProfile before the window closes
                if (onCloseCallback != null) {
                    onCloseCallback.accept(getChosenSettingsProfile());
                }
                dispose();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        xMinField = new javax.swing.JTextField();
        xMaxField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        yMaxField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yMinField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        zMaxField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zMinField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        speedField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        maxExtTempField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        defaultExtTempField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        maxBedTempField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        defaultBedTempField = new javax.swing.JTextField();
        tempCheckSlider = new javax.swing.JSlider();
        checkTempSliderLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        settingsProfileCombo = new javax.swing.JComboBox<>();
        saveProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Port:");

        jLabel3.setText("Prędkość połączenia:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(195, 195, 195))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Połączenie", jPanel2);

        jLabel4.setText("X min");

        xMinField.setText("0");
        xMinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMinFieldActionPerformed(evt);
            }
        });

        xMaxField.setText("200");
        xMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMaxFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("X max");

        yMaxField.setText("220");
        yMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yMaxFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Y max");

        yMinField.setText("0");
        yMinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yMinFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Y min");

        zMaxField.setText("150");
        zMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zMaxFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Z max");

        zMinField.setText("0");
        zMinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zMinFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Z min");

        jLabel12.setText("Wymiary stołu:");

        jLabel14.setText("Domyślna prędkość ruchu jałowego:");

        speedField.setText("30");
        speedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("mm/min.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(zMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(xMinField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(yMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(zMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(jLabel6)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(yMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(jLabel5)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(xMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(speedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel17))
                                                        .addComponent(jLabel12))))
                                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(xMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(xMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(yMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(yMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(zMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(zMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(speedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17))
                                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Wymiary drukarki", jPanel3);

        maxExtTempField.setText("260");
        maxExtTempField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxExtTempFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Maksymalna temperatura ekstrudera");

        defaultExtTempField.setText("200");
        defaultExtTempField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultExtTempFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Domyślna temperatura ekstrudera");

        maxBedTempField.setText("80");
        maxBedTempField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxBedTempFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Maksymalna temperatura stołu");

        jLabel16.setText("Domyślna temperatura stołu");

        defaultBedTempField.setText("50");
        defaultBedTempField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultBedTempFieldActionPerformed(evt);
            }
        });

        checkTempSliderLabel.setText("Sprawdzaj temperaturę co 5 sekund.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addComponent(checkTempSliderLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(tempCheckSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel15)
                                                                        .addComponent(jLabel16))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(defaultBedTempField)
                                                                        .addComponent(maxBedTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(441, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel13))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(defaultExtTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(maxExtTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(maxExtTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(defaultExtTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(maxBedTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(defaultBedTempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checkTempSliderLabel)
                                        .addComponent(tempCheckSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Temperatura", jPanel4);

        jLabel1.setText("Profil ustawień:");

        settingsProfileCombo.setEditable(true);
        settingsProfileCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        settingsProfileCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSettingsProfileComboActionPerformed(evt);
            }
        });

        saveProfile.setText("Zastosuj i zapisz");
        saveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsProfileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveProfile)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(settingsProfileCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveProfile))
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTabbedPane1)
                                                .addGap(707, 707, 707))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>// </editor-fold>//GEN-END:initComponents

    /**
     *  Utils methods
     *
     *
     *
     *
     */

    // przycisk zapisujący ustawienia do pliku
    private void saveProfileActionPerformed(java.awt.event.ActionEvent evt) {
        readFormFields();
        chosenSettingsProfile.saveProfileToFile(settingsPath);
        dispose();
    }
    private void readFormFields() {
        chosenSettingsProfile.setxMin(Integer.parseInt(xMinField.getText()));
        chosenSettingsProfile.setxMax(Integer.parseInt(xMaxField.getText()));
        chosenSettingsProfile.setyMin(Integer.parseInt(yMinField.getText()));
        chosenSettingsProfile.setyMax(Integer.parseInt(yMaxField.getText()));
        chosenSettingsProfile.setzMin(Integer.parseInt(zMinField.getText()));
        chosenSettingsProfile.setzMax(Integer.parseInt(zMaxField.getText()));
        chosenSettingsProfile.setSpeed(Integer.parseInt(speedField.getText()));
        chosenSettingsProfile.setMaxTempExt(Integer.parseInt(maxExtTempField.getText()));
        chosenSettingsProfile.setDefaultTempExt(Integer.parseInt(defaultExtTempField.getText()));
        chosenSettingsProfile.setMaxTempBed(Integer.parseInt(maxBedTempField.getText()));
        chosenSettingsProfile.setDefaultTempBed(Integer.parseInt(defaultBedTempField.getText()));
        chosenSettingsProfile.setCheckTempInterval(tempCheckSlider.getValue());
        chosenSettingsProfile.setBaudRate(Integer.parseInt(jComboBox3.getSelectedItem().toString()));
        chosenSettingsProfile.setProfileName(Objects.requireNonNull(settingsProfileCombo.getSelectedItem()).toString());
    }
    // wczytaj profil z pliku
    private void loadProfile(String profileName) {
        PrinterSettings loadedProfile = PrinterSettings.readProfileFromFile(settingsPath, profileName);
        if (loadedProfile != null) {
            System.out.println("Loaded profile: " + loadedProfile);
            chosenSettingsProfile = loadedProfile;
            settingsProfileCombo.setSelectedItem(loadedProfile.getProfileName());
            xMinField.setText(Integer.toString(loadedProfile.getxMin()));
            xMaxField.setText(Integer.toString(loadedProfile.getxMax()));
            yMinField.setText(Integer.toString(loadedProfile.getyMin()));
            yMaxField.setText(Integer.toString(loadedProfile.getyMax()));
            zMinField.setText(Integer.toString(loadedProfile.getzMin()));
            zMaxField.setText(Integer.toString(loadedProfile.getzMax()));
            speedField.setText(Integer.toString(loadedProfile.getSpeed()));
            maxExtTempField.setText(Integer.toString(loadedProfile.getMaxTempExt()));
            defaultExtTempField.setText(Integer.toString(loadedProfile.getDefaultTempExt()));
            maxBedTempField.setText(Integer.toString(loadedProfile.getMaxTempBed()));
            defaultBedTempField.setText(Integer.toString(loadedProfile.getDefaultTempBed()));
            tempCheckSlider.setValue(loadedProfile.getCheckTempInterval());
        }
        manageCOMPorts();
    }

    private void manageCOMPorts() {
        portsList = SerialPort.getCommPorts();
        Logger.getGlobal().info("Found " + portsList.length + " ports");

        jComboBox2.removeAllItems();
        for (SerialPort port : portsList) {
            jComboBox2.addItem(port.getSystemPortName());
        }

        if(chosenSettingsProfile.getPortName() != null) {
            Logger.getGlobal().info("Chosen port: " + chosenSettingsProfile.getPortName());
            for (SerialPort port : portsList) {
                if (port.getSystemPortName().equals(chosenSettingsProfile.getPortName())) {
                    jComboBox2.setSelectedItem(chosenSettingsProfile.getPortName());
                    break;
                }
            }

        } else {
            if(portsList.length > 0) {
                Logger.getGlobal().info("No port chosen, setting first available port");
                chosenSettingsProfile.setSerialPort(portsList[0].getSystemPortName());
                jComboBox2.setSelectedItem(portsList[0].getSystemPortName());
            }
        }

    }
    /**
     *  Action listeners
     *
     *
     *
     *
     */

    private void setSettingsProfileComboActionPerformed(java.awt.event.ActionEvent evt) {
        String profileName = settingsProfileCombo.getSelectedItem().toString();
        loadProfile(profileName);
    }

    private void xMinFieldActionPerformed(java.awt.event.ActionEvent evt) {
//        chosenSettingsProfile.setxMin(Integer.parseInt(xMinField.getText()));
    }

    private void xMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void yMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void yMinFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void zMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void zMinFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void maxExtTempFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void defaultExtTempFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void maxBedTempFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void defaultBedTempFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void speedFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public PrinterSettings getChosenSettingsProfile() {
        return chosenSettingsProfile;
    }



    // Variables declaration - do not modify
    private javax.swing.JLabel checkTempSliderLabel;
    private javax.swing.JTextField defaultBedTempField;
    private javax.swing.JTextField defaultExtTempField;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maxBedTempField;
    private javax.swing.JTextField maxExtTempField;
    private javax.swing.JButton saveProfile;
    private javax.swing.JComboBox<String> settingsProfileCombo;
    private javax.swing.JTextField speedField;
    private javax.swing.JSlider tempCheckSlider;
    private javax.swing.JTextField xMaxField;
    private javax.swing.JTextField xMinField;
    private javax.swing.JTextField yMaxField;
    private javax.swing.JTextField yMinField;
    private javax.swing.JTextField zMaxField;
    private javax.swing.JTextField zMinField;
    // End of variables declaration
}
